import Navbar from '../components/Navbar'
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <body>
        <Navbar /> {/*Навбар, должен быть на всех страницах*/}
        <Main /> {/*Pages как я понял*/}
        <NextScript />
      </body>
    </Html>
  )
}
